// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.WebAPI.Data;

namespace SmartSchool.WebAPI.Migrations
{
    [DbContext(typeof(SmartContext))]
    [Migration("20210613175304_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Matricula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(802),
                            DataNasc = new DateTime(1982, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(3826),
                            DataNasc = new DateTime(1982, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(3901),
                            DataNasc = new DateTime(1982, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(3911),
                            DataNasc = new DateTime(1982, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(3920),
                            DataNasc = new DateTime(1982, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(3935),
                            DataNasc = new DateTime(1982, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(3943),
                            DataNasc = new DateTime(1982, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Nota")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunoCurso");
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Nota")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(5626)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6593)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6622)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6625)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6627)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6633)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6635)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6636)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6638)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6642)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6644)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6645)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6647)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6649)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6651)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6653)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6655)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6658)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6660)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6661)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6663)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6665)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            Inicio = new DateTime(2021, 6, 13, 14, 53, 4, 1, DateTimeKind.Local).AddTicks(6667)
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Curso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Nutrição"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Administração"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Mecatrônica"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Biologia"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrerequisitoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PrerequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 0,
                            CursoId = 4,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 0,
                            CursoId = 5,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 0,
                            CursoId = 5,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Registro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 3, 994, DateTimeKind.Local).AddTicks(7272),
                            Nome = "Lauro",
                            Registro = 1,
                            Sobrenome = "Teste",
                            Telefone = "1111111"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 3, 996, DateTimeKind.Local).AddTicks(5082),
                            Nome = "Roberto",
                            Registro = 2,
                            Sobrenome = "Teste",
                            Telefone = "2222222"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 3, 996, DateTimeKind.Local).AddTicks(5155),
                            Nome = "Ronaldo",
                            Registro = 3,
                            Sobrenome = "Teste",
                            Telefone = "3333333"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 3, 996, DateTimeKind.Local).AddTicks(5159),
                            Nome = "Rodrigo",
                            Registro = 4,
                            Sobrenome = "Teste",
                            Telefone = "4444444"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataInicio = new DateTime(2021, 6, 13, 14, 53, 3, 996, DateTimeKind.Local).AddTicks(5161),
                            Nome = "Alexandre",
                            Registro = 5,
                            Sobrenome = "Teste",
                            Telefone = "55555555"
                        });
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoCurso", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.WebAPI.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool.WebAPI.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.WebAPI.Models.Disciplina", "Prerequisito")
                        .WithMany()
                        .HasForeignKey("PrerequisitoId");

                    b.HasOne("SmartSchool.WebAPI.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
