version: "3.8"

volumes:
        SmartShoolDb:
networks: 
    mysqlNET:
    smartschoolNET:

services:
    mysql: 
        image: "mysql:5.7"
        container_name: mysql
        ports: 
            - "3306:3306"
        volumes:
            - SmartShoolDb:/var/lib/mysql
        networks: 
            - mysqlNET
        environment:
            - MYSQL_PASSWORD=lalaland
            - MYSQL_ROOT_PASSWORD=lalaland
            - MYSQL_ROOT_HOST=% 
            - bind-adress:0.0.0.0
    smartschool:
        build:
            context: .
            dockerfile: dockerfile
        container_name: smartschool
        networks: 
            - mysqlNET
            - smartschoolNET
        ports: 
            - 5000:80
        environment:
            - DBSHOST=mysql
        depends_on: 
            - mysql